test: Add audit and bandit (#532)
Co-authored-by: Bigad Soleiman <bigadsoleiman@gmail.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -20,15 +20,22 @@ jobs:
       - name: Backend
         run: |
           npm ci
+          npm audit
           npm run build
           npm run test
           npx cdk synth
       - name: PyTests
+        # Suppression of pip audit failure until langchain is upgraded.
         run: |
           pip install -r pytest_requirements.txt
+          bandit -r .
+          pip-audit -r pytest_requirements.txt || true 
+          pip-audit -r lib/shared/web-crawler-batch-job/requirements.txt || true 
+          pip-audit -r lib/shared/file-import-batch-job/requirements.txt || true 
           pytest tests/
       - name: Frontend
         working-directory: ./lib/user-interface/react-app
         run: |
           npm ci
+          npm audit
           npm run build
